CREATE TABLE `ADDRESS` (
  `ADDRESS_ID` int(11),
  `ADDRESS_STREET` varchar(250) default NULL,
  `ADDRESS_HOUSENUMBER` varchar(15) default NULL,
  `ADDRESS_POSTCODE` int(5),
  `ADDRESS_CITY` varchar(50) default NULL,
  PRIMARY KEY  (`ADDRESS_ID`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1; 

CREATE TABLE `CARD` (
  `CARD_SEQUENCE_NUMBER` int(11) NOT NULL,
  `CARD_NUMBER_FIRST` varchar(12) default NULL,
  `CARD_NUMBER_SECOND` varchar(4) default NULL,
  `CARD_PHONE_NR_FIRST` varchar(3) default NULL,
  `CARD_PHONE_NR_SECOND` varchar(9) default NULL,
  `CARD_CUSTOMER_ORDER_NUMBER` varchar(12) default NULL,
  `CARD_STATUS` varchar(15) default NULL,
  `CARD_ORDER_NUMBER` int(12),
  `CARD_DELIVERY_SLIP_DATE` date,
  `CARD_DELIVERY_SLIP_NUMBER` int(12),   
  `CARD_PERSON` int(11),
  `CARD_CUSTOMER` int(11),
  PRIMARY KEY  (`CARD_SEQUENCE_NUMBER`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

 

CREATE TABLE `PERSON` (
  `PERSON_ID` int(11),
  `PERSON_NAME` varchar(50) default NULL,
  `PERSON_FIRSTNAME` varchar(50) default NULL,
  `PERSON_GENDER` varchar(5) default NULL,
  `PERSON_ADD_EQUALS_INST_ADD` varchar(1) default NULL,
  PRIMARY KEY  (`PERSON_ID`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;


CREATE TABLE `CUSTOMER` (
  `CUSTOMER_ID` int(11),
  `CUSTOMER_NAME` varchar(50) default NULL,
  `CUSTOMER_BRANCH` varchar(50) default NULL,
  `CUSTOMER_ADDRESS` int(11),
  PRIMARY KEY  (`CUSTOMER_ID`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;